---
title: "Funfair"
output:
  html_document:
    df_print: paged
  pdf_document: default
---






PART 1 

```{r}
raw_data <- read.csv(file = 'networkfunfairTX.txt', header = F, sep = ' ')
colnames(raw_data) <- c("Buyer", "Seller", "Timestamp", "TokenAmount")
message ('The number of rows are: ', nrow(raw_data))
```
```{r}
summary(raw_data)
```
```{r}
Total_circulation_amount = 6548879189 * 10^8
outliers <- subset(raw_data, TokenAmount > Total_circulation_amount)
message ('The number of outliers in the dataset are: ', nrow(outliers))
```
```{r}
preprocessed_data <- subset(raw_data, TokenAmount <= Total_circulation_amount)
summary(preprocessed_data)
```
```{r}
library(plyr)
Buyer_Seller_Pair_Frequencies <- ddply(preprocessed_data, .(preprocessed_data$Buyer, preprocessed_data$Seller), nrow)
names(Buyer_Seller_Pair_Frequencies) <- c("Buyer", "Seller", "Frequency")
Buyer_Seller_Pair_Frequencies
```
```{r}
summary(Buyer_Seller_Pair_Frequencies)
message ('Variance: ', var(Buyer_Seller_Pair_Frequencies$Frequency))
message ('Standard Deviation: ', sd(Buyer_Seller_Pair_Frequencies$Frequency))
```
```{r}
freq <- Buyer_Seller_Pair_Frequencies$Frequency
library(MASS)

h <- hist(freq, main = 'Frequency Pair Distribution',
     xlab = 'Frequencies', ylab = 'Number of pairs', col = 'pink',
     breaks = 1000, xlim = c(0, 100), ylim = c(0, 1000))
```
```{r}
h <- hist(freq, main = 'Frequency Pair Distribution with exponential fit',
     xlab = 'Frequencies', ylab = 'Number of pairs', col = 'lightblue', freq = FALSE,
     breaks = 1000, xlim = c(0, quantile(freq, 0.99)))

fit <- fitdistr(freq, 'exponential')
curve(dexp(x, rate = fit$estimate), from = 0, col = 'red', add = TRUE, lwd = 2)
```
```{r}
library(fitdistrplus)
fit_w  <- fitdist(freq, "weibull")
fit_ln <- fitdist(freq, "lnorm")
fit_ex <- fitdist(freq, "exp")

par(mfrow=c(2,2))
plot.legend <- c("Weibull", "lognormal", "exponential")
denscomp(list(fit_w, fit_ex, fit_ln), legendtext = plot.legend)
cdfcomp (list(fit_w, fit_ex, fit_ln), legendtext = plot.legend)
qqcomp  (list(fit_w, fit_ex, fit_ln), legendtext = plot.legend)
ppcomp  (list(fit_w, fit_ex, fit_ln), legendtext = plot.legend)
```

PART 2 BEGINS HERE

```{r}
preprocessed_data$TokenAmount <- preprocessed_data$TokenAmount/10^8
Time <- as.Date(as.POSIXct(preprocessed_data$Timestamp, origin = '1970-01-01'))
preprocessed_data$Timestamp <- Time
preprocessed_data
```
```{r}
library("readxl")
my_data <- read_excel("FunFair_CoinMarketCap.xlsx")
colnames(my_data) <- c('Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume', 'MarketCap')
my_data$Timestamp <- as.Date(my_data$Timestamp, "%d%B%Y")
my_data$MarketCap <- as.double(my_data$MarketCap)
my_data
```
```{r}
new_data <- preprocessed_data[order (- preprocessed_data$TokenAmount),]
new_data$Seller <- NULL
new_data
```
```{r}
joined_df <- join(new_data, my_data)
joined_df <- na.omit(joined_df)
joined_df
```
```{r}
joined_df$percentage <- (joined_df$TokenAmount/joined_df$MarketCap)*100
joined_df
```
```{r}
Top_Buyers <- subset(joined_df, percentage < 100)
track_k_buyers <- head(Top_Buyers, 70)
nk <- (unique(track_k_buyers))
Top_Buyers
```

```{r}
message('The value of K is: ',nrow(count(nk)))
```

```{r}
cor.test(track_k_buyers$TokenAmount, track_k_buyers$MarketCap, method = "pearson")
cor.test(Top_Buyers$Open, Top_Buyers$High, method = "pearson")
cor.test(Top_Buyers$Close, Top_Buyers$High, method = "pearson")
```
```{r}
linearModOH <- lm(Open ~ High, data=Top_Buyers)  # build linear regression model on full data
linearModCH <- lm(Close ~ High, data=Top_Buyers)
linearModTM <- lm(Close ~ High, data=Top_Buyers)
summary(linearModOH)
```
```{r}
modelSummary <- summary(linearModOH)  # capture model summary as an object
modelCoeffs <- modelSummary$coefficients  # model coefficients
modelCoeffs


```
```{r}
plot(Top_Buyers$Open, Top_Buyers$High, pch = 16, cex = 1.3, col = "blue", main = "Open vs High", xlab = "Open", ylab = "High")
abline(lm(Top_Buyers$Open ~Top_Buyers$High), col = 'red')
```
```{r}
plot(Top_Buyers$Close, Top_Buyers$High, pch = 16, cex = 1.3, col = "blue", main = "Close vs High", xlab = "Open", ylab = "High")
abline(lm(Top_Buyers$Close ~Top_Buyers$High), col = 'red')
```
```{r}
plot(linearModOH)
plot(linearModCH)
plot(linearModTM)
```


